# Trimming

## Installing and Executing Seqtk

Toolkit for processing sequences in FASTA/Q formats

    git clone https://github.com/lh3/seqtk
    cd seqtk; make
    ./seqtk seq -A /opt/data/opt/data/fastq/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq.gz > test.fasta
    /opt/tools/seqtk/seqtk seq -A \ /opt/data/fastq/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq.gz  > test.fasta
    /opt/tools/seqtk/seqtk trimfq -l 20 /opt/data/fastq/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq.gz \ > /opt/data/fastq-trimming/out/trimmed-seqtk.fq


## Executing FASTX

### FASTQC Before
    /opt/tools/FastQC/fastqc /opt/data/fastq/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq.gz --outdir test
### FASTX
    /opt/tools/fastx/bin/fastx_trimmer -v -f 7 -l 100 -Q 33 -i /opt/data/fastq-trimming/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq -o /opt/data/fastq-trimming/out/trimmed-fastx.fq

### FASTQC After

 /opt/tools/FastQC/fastqc /opt/data/fastq-trimming/out/trimmed-fastx.fq --outdir test
