# Trimming of FASTQ

A lot of different tools exist for trimming. Easiest way is to google after "fastq trimming". Here, we present two tools:

## Task 1: Installing and Executing Seqtk

Toolkit for processing sequences in FASTA/Q formats

    git clone https://github.com/lh3/seqtk
    cd seqtk; make
    ./seqtk seq -A /opt/data/fastq/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq.gz > test.fasta
    /opt/tools/seqtk/seqtk trimfq -l 20 /opt/data/fastq/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq.gz \ > trimmed-seqtk.fq

## Task 2: Try to understand what the command did
Enter the following command and try to find the `-l` option
          
          /opt/tools/seqtk/seqtk trimfq

## Task 3: Run it with FastQC
Check graphically what it actually did. First execute command, than download results.
        
        /opt/tools/FastQC/fastqc trimmed-seqtk.fq --outdir test

## Task 4: Executing FASTX and understand the command

Try to understand the commands, execute them and alter them. Check out the [website](http://hannonlab.cshl.edu/fastx_toolkit/commandline.html#fastx_trimmer_usage) for help!
### FASTQC Before
    /opt/tools/FastQC/fastqc /opt/data/fastq/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq.gz --outdir test
### FASTX
    /opt/tools/fastx/bin/fastx_trimmer -v -f 7 -l 100 -Q 33 -i /opt/data/fastq-trimming/LPA-Plasmid-long-50-1-LongAmp-NEB_S78_L001_R1_001.fastq -o trimmed-fastx.fq
### FASTQC After
    /opt/tools/FastQC/fastqc trimmed-fastx.fq --outdir test

## Task 5: Execute a Quality Filter

Execute the quality-filter command (/opt/tools/fastx/bin/fastq_quality_filter) and filter reads with a quality lower then 28. Please add the command line option -Q 33. Check out the [website](http://hannonlab.cshl.edu/fastx_toolkit/commandline.html#fastq_quality_filter_usage) for help! Execute the FASTQ report afterwards (as before).

## Advanced Bash Scripting

```sh
for file in /home/sebastian/*
do
# do something on $file
echo "$file"
done
```
